In [ ]:
# define sims once for each exercise may help

In [ ]:
# Q1: How likely is it that you roll doubles when rolling two dice?

# Q2: If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of 
# -getting more than 3 heads?

# Q3: There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# -Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards 
# -I drive past both have data science students on them?

# Q4: Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the 
# -snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I 
# -will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use 
# -the np.random.normal) You'll need to make a judgement call on how to handle some of your values

# Q5: Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

# Q6: When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
# -What is the probability that we observe an installation issue within the first 150 students that download anaconda?
# -How likely is it that 450 students all download anaconda without an issue?

# Q7: There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# -However, you haven't seen a food truck there in 3 days. How unlikely is this?
# -How likely is it that a food truck will show up sometime this week?

# Q8: If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [172]:
import pandas as pd

In [73]:
# Q1:
# both_dice = [1,2,3,4,5,6], [1,2,3,4,5,6] - dont need
first_dice = [1,2,3,4,5,6]
# second_dice = [1,2,3,4,5,6] - dont need

di_trial = 2
di_sim = 10_000

In [ ]:
# the_di = np.random.choice(first_dice, size=(di_sim, di_trial))
# the_di

In [75]:
the_di = np.random.choice(first_dice, (di_sim, di_trial))
the_di

array([[3, 1],
       [6, 3],
       [6, 5],
       ...,
       [2, 4],
       [5, 2],
       [2, 4]])

In [83]:
di_df = pd.DataFrame(the_di)
di_df

0  1
0     3  1
1     6  3
2     6  5
3     1  3
4     6  3
...  .. ..
9995  6  1
9996  5  4
9997  2  4
9998  5  2
9999  2  4

[10000 rows x 2 columns]

In [84]:
di_df[1]

0       1
1       3
2       5
3       3
4       3
       ..
9995    1
9996    4
9997    4
9998    2
9999    4
Name: 1, Length: 10000, dtype: int64

In [86]:
bothdi = di_df[(di_df[0] == di_df[1])]
bothdi

0  1
11    5  5
19    3  3
20    6  6
24    1  1
25    4  4
...  .. ..
9965  2  2
9973  2  2
9978  3  3
9989  4  4
9992  5  5

[1682 rows x 2 columns]

In [88]:
len(bothdi) / len(di_df)

0.1682

In [ ]:
#(di_df[0] == di_df[1]).mean()

In [187]:
di_df.iat[0,0]

3

In [ ]:
# Q2 "more than 3 heads":
# expected probability is 37.5%

In [53]:
coin = ['H','T']

coin_sim = 10_000

coin_trials = 8

In [78]:
coins_3 = np.random.choice(coin, (coin_sim, coin_trials))
coins_3

array([['H', 'T', 'H', ..., 'T', 'H', 'H'],
       ['T', 'T', 'T', ..., 'H', 'T', 'H'],
       ['T', 'H', 'H', ..., 'T', 'H', 'T'],
       ...,
       ['H', 'H', 'H', ..., 'T', 'H', 'H'],
       ['H', 'T', 'T', ..., 'T', 'T', 'H'],
       ['H', 'H', 'H', ..., 'T', 'H', 'T']], dtype='<U1')

In [127]:
coin_df = pd.DataFrame(coins_3)
coin_df

0  1  2  3  4  5  6  7
0     H  T  H  T  H  T  H  H
1     T  T  T  H  T  H  T  H
2     T  H  H  T  T  T  H  T
3     T  H  T  H  T  T  T  H
4     T  T  T  H  T  H  H  T
...  .. .. .. .. .. .. .. ..
9995  H  H  H  H  H  T  T  T
9996  T  H  H  H  T  T  H  H
9997  H  H  H  T  H  T  H  H
9998  H  T  T  T  T  T  T  H
9999  H  H  H  H  H  T  H  T

[10000 rows x 8 columns]

In [128]:
coin_df[coin_df['H'] > 3]

KeyError: 'H'

In [129]:
coin_df == 'H'

0      1      2      3      4      5      6      7
0      True  False   True  False   True  False   True   True
1     False  False  False   True  False   True  False   True
2     False   True   True  False  False  False   True  False
3     False   True  False   True  False  False  False   True
4     False  False  False   True  False   True   True  False
...     ...    ...    ...    ...    ...    ...    ...    ...
9995   True   True   True   True   True  False  False  False
9996  False   True   True   True  False  False   True   True
9997   True   True   True  False   True  False   True   True
9998   True  False  False  False  False  False  False   True
9999   True   True   True   True   True  False   True  False

[10000 rows x 8 columns]

In [131]:
num_of_h = (coin_df == 'H').sum(axis=1)
num_of_h

0       5
1       3
2       3
3       3
4       3
       ..
9995    5
9996    5
9997    6
9998    2
9999    6
Length: 10000, dtype: int64

In [133]:
(num_of_h > 3).mean()

0.6335

In [ ]:
# Q3 "both billboards have a DS student":

In [ ]:
# expected probability is 6.25%

In [63]:
cohort = ['W', 'W', 'W', 'D']

cohort_sim = 10_000

cohort_trial = 2

In [65]:
cohort_chance = np.random.choice(cohort, (cohort_sim, cohort_trial))
cohort_chance

array([['D', 'D'],
       ['W', 'D'],
       ['W', 'W'],
       ...,
       ['W', 'D'],
       ['W', 'W'],
       ['W', 'W']], dtype='<U1')

In [107]:
cohort_df = pd.DataFrame(cohort_chance)
cohort_df

0  1
0     D  D
1     W  D
2     W  W
3     D  W
4     W  W
...  .. ..
9995  W  W
9996  W  W
9997  W  D
9998  W  W
9999  W  W

[10000 rows x 2 columns]

In [108]:
cohort_col1 = cohort_df[0].T
cohort_col1

0       D
1       W
2       W
3       D
4       W
       ..
9995    W
9996    W
9997    W
9998    W
9999    W
Name: 0, Length: 10000, dtype: object

In [117]:
first_billboard = (cohort_df[0] == 'D')
second_billboard = (cohort_df[1] == 'D')
print(first_billboard)
print(second_billboard)

0        True
1       False
2       False
3        True
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Name: 0, Length: 10000, dtype: bool
0        True
1        True
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997     True
9998    False
9999    False
Name: 1, Length: 10000, dtype: bool


In [126]:
f = (first_billboard(True) == second_billboard(True))
f

TypeError: 'Series' object is not callable

In [111]:
both_ds = cohort_df[(cohort_df[0] == cohort_df[1])]
both_ds

0  1
0     D  D
2     W  W
4     W  W
5     W  W
6     W  W
...  .. ..
9994  W  W
9995  W  W
9996  W  W
9998  W  W
9999  W  W

[6254 rows x 2 columns]

In [112]:
len(both_ds)

6254

In [113]:
len(both_ds) / len(cohort_df)

0.6254

In [137]:
#test
np.random.choice(cohort, size=(cohort_sim, cohort_trial))

array([['W', 'W'],
       ['W', 'D'],
       ['W', 'W'],
       ...,
       ['W', 'D'],
       ['W', 'W'],
       ['D', 'W']], dtype='<U1')

In [138]:
(cohort_df == 'D').sum(axis=1) == 2).mean()

0      1
0      True   True
1     False   True
2     False  False
3      True  False
4     False  False
...     ...    ...
9995  False  False
9996  False  False
9997  False   True
9998  False  False
9999  False  False

[10000 rows x 2 columns]

In [ ]:
# Q4:

In [139]:
std = 1.5
mean = 3
days = 5

In [141]:
poptart_per_day = np.random.normal(mean, std, (cohort_sim, days))
poptart_per_day

array([[ 4.19187367,  0.58085459,  1.85532434,  5.19991184,  2.47263448],
       [ 3.42225938,  3.22837898,  4.52217805,  2.37709551,  2.59628906],
       [ 3.53035602, -1.05310612,  0.57357473,  1.24583895,  2.0583156 ],
       ...,
       [ 4.65197213,  2.82490602,  1.67959355,  1.83702551,  3.63585701],
       [ 4.627642  ,  3.91238791,  3.17560353,  4.48270408,  4.20024255],
       [ 3.4814067 ,  1.46968496,  2.48571547,  4.16237386,  3.78025564]])

In [142]:
poptart_per_week = poptart_per_day.sum(axis=1)
poptart_per_week

array([14.30059891, 16.14620098,  6.35497917, ..., 14.62935421,
       20.39858008, 15.37943662])

In [143]:
(poptart_per_week < 16).mean()

0.6128

In [ ]:
# Q5:
# np.random.normal: generates numbers from a normal distribution with a specified mean and standard deviation

In [147]:
w_std = 6
m_std = 8
m_height = 178
w_height = 170

In [145]:
men_height = np.random.normal(m_height, m_std, cohort_sim)
men_height

array([175.43661441, 174.81422754, 178.43421762, ..., 185.96198208,
       189.67902406, 184.6661059 ])

In [148]:
women_height = np.random.normal(w_height, w_std, cohort_sim)
women_height

array([172.55261168, 169.41963305, 166.04397176, ..., 163.43327916,
       167.34539488, 165.90649014])

In [150]:
(women_height > men_height).mean()

0.2049

In [ ]:
# Q6:

In [151]:
students = 50
conda = ['Win', "Lose"]

In [154]:
student_sim = np.random.choice(conda, (cohort_sim, students), p = [249/250, 1/250])
student_sim

array([['Win', 'Win', 'Win', ..., 'Win', 'Win', 'Win'],
       ['Win', 'Win', 'Win', ..., 'Win', 'Win', 'Win'],
       ['Win', 'Win', 'Win', ..., 'Win', 'Win', 'Win'],
       ...,
       ['Win', 'Win', 'Win', ..., 'Win', 'Win', 'Win'],
       ['Win', 'Win', 'Win', ..., 'Win', 'Win', 'Win'],
       ['Win', 'Win', 'Win', ..., 'Win', 'Win', 'Win']], dtype='<U4')

In [155]:
((student_sim == 'Win').sum(axis=1) == 50).mean()

0.8162

In [188]:
((student_sim == 'Win').sum(axis=1) == 100).mean()

0.0

In [ ]:
# Q7:

In [ ]:
# Q8: 23 in room, odds that two share a birthday?

In [164]:
in_room20 = 20
in_room40 = 40
in_room23 = 23
birthday = range(0,365)

In [179]:
birthdays = pd.DataFrame(np.random.choice(birthday, (cohort_sim, in_room23)))
birthdays

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      47  271  161  270  163  330   14   14  236   68  ...  302    6   80   
1      43  305  301  178  295  347  145  198  223   58  ...   44   73  279   
2      75  310   90  101  154  198  348   95  197  133  ...  272  226  226   
3     117  207  275   43  274  142  299  103   81  158  ...  194  112  346   
4     182  283  219  339   76   52  222  184  146  274  ...  158  334   84   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  248   85  228   36   20   48  208  247  270  130  ...  217  258   74   
9996  234  126   50  330   62    1   42  236  245  257  ...  205  233  301   
9997  148  220  304   62  100  258  194  195  173   24  ...   37   33  292   
9998  228   26  274  337  124   19   21  216  263  206  ...   35   10  321   
9999  207  133   86  267  164  123   84   68  124  356  ...   98  325  302   

       16   17   18   19   20   21   22  
0      10  304   78  230   54   89   80  
1     115  276   85  188  263  134  163  
2     358  361  174   11  251   93  294  
3     221  341  286  256  258   16  252  
4     226  216  326   32  202  336   31  
...   ...  ...  ...  ...  ...  ...  ...  
9995   46   70  338   78  350  181  335  
9996  208  255  350   54   84   56  210  
9997   82  187  125   76  340   23   68  
9998   97   50   35   73  289  352  230  
9999  294  350   52  114  182  294  116  

[10000 rows x 23 columns]

In [190]:
unq_bd = birthdays.nunique(axis=1)

In [196]:
(unq_bd < 23).mean()

0.5156

In [49]:
# test
def dice_roll(d):
    return np.random.randint(1,6)

dice_roll(4)

2

In [174]:
%matplotlib inline
import numpy as np
import pandas as pd
#import viz # curriculum example visualizations

np.random.seed(29)

In [ ]:
# The numpy.random module provides a number of functions for generating random numbers.

# np.random.choice: selects random options from a list
# np.random.uniform: generates numbers between a given lower and upper bound
# np.random.random: generates numbers between 0 and 1
# np.random.randn: generates numbers from the standard normal distribution
# np.random.normal: generates numbers from a normal distribution with a specified mean and standard deviation

In [ ]:
outcomes = [1,2,3,4,5,6]
n_simulations = 

In [ ]:
np.random.choice(outcomes, n_simulations)

In [2]:
ht_outcome = ['H','T']
ht_simulation = 100_000
ht_trials = 3

In [7]:
heads_or_tails = np.random.choice(ht_outcome, (ht_simulation, ht_trials))

In [8]:
heads_or_tails

array([['H', 'H', 'T'],
       ['T', 'T', 'T'],
       ['T', 'T', 'H'],
       ...,
       ['T', 'H', 'T'],
       ['T', 'H', 'H'],
       ['H', 'H', 'H']], dtype='<U1')

In [9]:
len(heads_or_tails)

100000

In [ ]:
heads_or_tails

In [13]:
tails_count = (heads_or_tails == 'T').sum(axis=1)

In [15]:
(heads_or_tails == 'T').sum()

150078

In [11]:
tails_count

array([1, 3, 2, ..., 2, 1, 0])

In [16]:
# Game of chance

In [17]:
dice_choices = [1,2,3,4,5,6]
sims = 100_000
dice_trials = 3

In [19]:
'''Rolling the three dice 100,000 times'''
rolling = np.random.choice(dice_choices, (sims, dice_trials))
rolling

array([[4, 1, 3],
       [1, 4, 5],
       [2, 2, 3],
       ...,
       [6, 3, 2],
       [4, 3, 3],
       [5, 1, 6]])

In [20]:
rolling.sum()

1050316

In [21]:
rolling.sum(axis=1)

array([ 8, 10,  7, ..., 11, 10, 12])

In [25]:
nap_p = 0.3
day = 2
nap_sim = 100_000

In [27]:
data = np.random.random((nap_sim, day))
data

array([[0.34304566, 0.9372552 ],
       [0.71886922, 0.90707257],
       [0.90861645, 0.4828345 ],
       ...,
       [0.98309977, 0.90468091],
       [0.26081892, 0.18396546],
       [0.35915965, 0.02579447]])

In [29]:
data < nap_p

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [ True,  True],
       [False,  True]])

In [28]:
naps = (data < nap_p).sum(axis=1)
naps

array([0, 0, 0, ..., 0, 2, 1])

In [60]:
import math.pyplot as plt

ModuleNotFoundError: No module named 'math.pyplot'; 'math' is not a package

In [186]:
# two dice
import random
def problem(): 
    random.seed(82)
    for i in range(100):
        k=random.randint(1,6)
        for j in range(100):
            a=random.randint(1,6)
            s=a+k
            print(s)

problem()

6
7
5
4
4
8
5
4
3
6
6
7
3
4
5
7
4
3
6
3
8
5
5
6
3
6
4
3
4
5
8
5
3
7
5
7
8
6
6
6
5
8
6
8
5
3
5
5
3
8
4
5
3
4
3
5
3
8
3
7
8
5
3
6
8
7
6
3
5
5
7
4
8
8
3
8
6
6
3
3
7
6
8
5
7
6
3
5
3
8
6
6
6
6
5
7
3
8
8
8
11
10
9
8
12
11
7
7
10
10
12
9
8
8
10
12
10
11
8
12
9
9
12
8
8
9
10
12
8
12
10
8
7
8
12
7
12
11
9
12
10
9
12
8
11
9
8
10
10
11
10
9
8
7
12
7
12
8
12
9
9
11
11
7
11
12
8
8
9
7
9
12
9
10
9
12
10
10
8
10
7
7
7
8
10
8
7
8
9
12
7
11
7
12
12
10
9
7
7
8
4
7
8
9
9
4
7
6
4
8
5
4
8
8
8
9
7
6
5
4
5
4
6
8
7
5
4
5
5
6
7
4
7
4
5
9
7
7
7
8
9
9
4
4
4
6
5
7
8
5
6
9
6
4
6
4
7
6
4
6
6
4
8
5
4
6
7
6
8
9
4
4
5
8
9
5
7
6
9
9
9
8
7
6
5
4
4
4
7
5
7
7
8
5
4
8
9
8
7
9
2
2
4
2
7
5
4
6
4
5
3
5
4
7
7
5
7
3
7
4
3
5
4
3
3
4
4
7
5
4
4
3
2
7
7
4
5
5
4
6
2
3
6
5
3
7
6
5
4
4
5
2
3
6
5
2
7
7
2
3
5
2
6
7
7
5
7
7
3
7
7
3
6
6
6
2
3
2
7
6
7
2
2
2
6
5
2
5
7
4
7
3
3
3
4
3
4
7
5
7
8
10
5
8
5
9
10
9
6
7
8
5
6
6
7
10
6
9
10
9
10
10
9
6
5
5
5
5
9
6
10
5
10
6
9
9
7
8
5
9
9
7
9
9
7
7
8
9
5
7
8
10
10
9
7
6
10
7
6
10
8
10
7
6
10
6
10
6
10

7
7
7
5
7
3
4
5
5
6
3
8
5
7
8
3
8
7
3
3
3
5
6
4
4
9
6
9
9
6
7
7
4
5
5
6
9
6
9
5
5
5
4
4
7
8
6
7
8
6
6
8
9
8
9
6
8
5
8
6
8
5
7
6
6
7
9
7
5
8
5
5
4
6
7
8
7
5
6
4
6
6
5
5
9
8
9
9
4
7
6
8
4
5
4
8
9
7
5
4
5
7
7
4
8
5
9
9
7
7
9
8
7
9
8
9
4
6
7
9
9
9
10
6
5
5
7
7
6
7
5
9
9
9
5
9
9
7
7
10
5
6
9
7
5
5
8
10
7
8
10
6
9
6
6
5
6
5
7
5
6
8
8
9
8
10
7
9
6
5
6
7
7
5
9
9
9
5
6
5
7
10
10
6
10
9
5
10
6
5
10
5
10
6
9
5
7
7
6
5
5
10
8
5
8
6
8
10
5
10
10
5
10
10
6
6
10
5
10
8
5
8
7
8
9
8
10
7
7
8
8
6
9
6
10
5
6
9
10
6
5
5
10
9
5
9
10
5
8
8
5
7
5
10
6
8
7
9
7
8
9
6
8
9
10
7
6
10
8
8
8
6
10
5
5
7
9
7
9
5
8
10
7
9
10
9
8
9
5
7
7
5
8
9
10
8
9
5
9
8
6
8
6
9
5
10
9
8
9
6
9
8
6
7
7
8
6
7
7
9
10
10
9
6
10
11
7
10
9
7
9
6
6
7
7
9
10
8
7
7
11
10
9
8
9
6
9
7
11
10
10
9
11
7
7
6
6
11
6
8
10
11
10
7
10
7
10
8
9
9
6
6
10
7
11
6
9
6
6
6
9
8
10
11
9
11
11
11
11
7
11
11
8
7
7
9
8
9
6
11
6
7
8
7
11
6
11
6
9
9
11
11
6
7
8
9
6
9
6
11
6
2
4
2
7
4
5
7
6
6
3
5
3
4
3
2
2
3
6
6
2
4
6
7
3
2
3
5
5
6
5
6
2
2
5
4
4
7
6
4
5
3
4
2
7
6
6


7
6
6
9
7
8
9
5
7
7
5
6
8
9
10
6
5
6
10
8
6
9
8
7
7
5
9
8
10
8
8
7
8
9
10
6
7
7
5
10
6
10
10
9
6
7
8
9
6
8
6
7
5
10
7
8
8
5
6
8
5
7
7
6
5
8
9
9
5
8
7
8
9
10
9
9
5
6
7
8
10
10
10
7
6
9
9
8
6
9
8
10
10
7
6
6
9
6
9
5
8
5
6
7
10
5
7
8
7
6
6
9
6
6
8
9
5
10
6
5
10
5
8
6
8
9
9
10
11
6
9
7
9
11
9
9
11
11
11
10
6
9
7
11
7
9
9
11
11
10
11
7
11
7
9
10
9
9
9
7
6
8
8
10
10
9
6
7
8
9
11
8
6
8
9
10
7
11
9
11
8
9
10
7
10
10
6
7
6
11
10
11
6
8
8
10
9
10
7
11
6
10
7
11
8
7
10
11
10
7
9
8
8
7
6
6
7
11
8
10
9
6
9
5
7
6
6
10
6
8
8
5
6
7
6
7
7
5
5
8
7
5
9
10
8
7
10
6
7
5
5
5
7
10
6
9
5
6
5
10
10
9
6
9
8
9
6
7
7
9
8
9
8
8
8
10
10
6
7
5
7
7
9
10
5
8
9
9
8
5
7
9
9
5
9
9
7
6
6
7
8
8
7
9
5
6
6
8
7
6
7
10
10
8
5
9
9
10
7
6
6
10
10
6
3
3
6
7
6
3
6
7
5
5
6
3
4
5
4
4
4
3
8
4
3
3
6
6
6
8
5
5
8
3
6
3
5
4
7
3
5
5
6
3
3
4
3
3
4
3
4
8
3
6
3
6
7
8
7
3
3
4
3
5
5
4
4
8
3
6
8
5
6
8
6
5
4
6
5
8
7
6
4
3
5
6
5
7
4
7
7
6
6
7
7
6
8
6
8
3
4
4
6
2
5
4
2
4
2
5
7
4
4
4
7
6
5
7
2
4
6
6
4
3
2
4
5
4
6
7
5
5
6
7
2
7
3
5
6
7
2
7
7
6
6
5
4